### PR TITLE
Move tsconfig.json to root

### PR DESCRIPTION
**Pull request by lipis**
The rest of the common configuration files are in the root, so let's keep them all in one place

### CODE REVIEW

**Comment by bennyn** [comment]
My idea was to actually put all the configs in the `config` directory^^

**Comment by bennyn** [comment]
@lipis If you resolve the conflicts, I will merge it. :D

**Comment by lipis** [comment]
Done! 🍻 🍺

**Comment by bennyn** [comment]
Looks like it doesn't work with `@wireapp/cbor`. 😢

**Comment by lipis** [comment]
What's so special with `cbor`?

**Comment by bennyn** [comment]
`proteus` and `core` have been still referencing `"../../configs/tsconfig.json"`.

**Comment by lipis** [comment]
👍

**Pull request merged**
