### PR TITLE
chore(react-ui-kit): Add Brand icons (GitHub, Facebook, Twitter, Link…

### PR DESCRIPTION
**Pull request by lipis**
…edIn)

### CODE REVIEW

**Comment by gregor** [comment]
If I understood Benny's comment in the chat correctly I think he was looking for creating new namespace Brandicon to include these in and keep them seperate from our own icons.

**Comment by gregor** [comment]
Let's have @bennyn add his own 2 cents. Not sure if I understood his comment in the intended way.

**Comment by bennyn** [comment]
Gregor understood it correctly. I think we should separate "third party" icons from our icons, so let's move them to `src/Icon/Brand` or something similar.

**Comment by lipis** [comment]
@bennyn changed..

**Pull request merged**
