### PR TITLE
feat(bot-api): Send text to all group conversations

### PR DESCRIPTION
**Pull request by bennyn**
## Pull Request Checklist

- [ ] My code is covered by tests
- [x] I will [merge the PR as breaking change](https://github.com/wireapp/wire-web-packages/wiki/Releases#create-major-release), if the API contract changes

### CODE REVIEW

**Comment by bennyn** [comment]
Possible solutions:

**Function Overloads**

```typescript
public async sendText(text: string, conversationId: string): Promise<void>;
public async sendText(text: string, conversationIds: string[]): Promise<void>;
public async sendText(text: string, type?: CONVERSATION_TYPE): Promise<void>;
public async sendText(text: string, conversationType: string | string[] | CONVERSATION_TYPE | undefined): Promise<void> {
  ...
}
```

**DSL**

```js
sendText(text).toConversation(id);
sendText(text).toConversations([id, id]);
sendText(text).toConversationType(REGULAR);
sendText(text).toAllConversations();
```

**Separate functions**

```js
sendTextToConversation(text, id);
sendTextToConversations(text, [id, id]);
sendTextToConversationType(text, REGULAR);
sendTextToAllConversations(text);
```

**Comment by ffflorian** [comment]
I vote for function overloading.

**Comment by bennyn** [comment]
I prefer the **DSL**.

**Comment by ffflorian** [comment]
Since we have the **DSL** in place with `withMentions`, I change my vote in favor of the **DSL**.

**Pull request closed without merging**
